### ISSUE TITLE
useSessionStorage error 

### ISSUE THREAD

**Issue by princej02** [PacktPublishing/Building-Micro-Frontends-with-React-18#9]
I am going through the book and followed instructions on how the hook was made and when using it i get an error in the application. 
Cannot read properties of null (reading 'useCallback'). It keeps pointing to this part of the code.
const readValue = useCallback((): T => {
    // Prevent build error "window is undefined" but keep keep working
    if (typeof window === 'undefined') {
      return initialValue;
    }

    try {
      const item = window.sessionStorage.getItem(key);
      return item ? (parseJSON(item) as T) : initialValue;
    } catch (error) {
      console.warn(`Error reading sessionStorage key “${key}”:`, error);
      return initialValue;
    }
  }, [initialValue, key]);

**Comment by areai51** [comment]
it could be due to a change in the package versions could you push your code to a github repo and send me a link to it

**Comment by bsingha27** [comment]
Hi @princej02, we're closing this issue for now, if you encounter any further issues, you're welcome to open a new one.
